### ISSUE TITLE
Error with latest version

### ISSUE THREAD

**Issue by henfri** [nielstron/pyblnet#18]
Hello,

I just tested the latest version.
With that, I get this error.
Traceback (most recent call last):
  File "H:/HeimNetzwerk/UVR/pyblnet_updated_orig/pyblnet/example.py", line 47, in <module>
    print(blnet.get_latest())
  File "H:\HeimNetzwerk\UVR\pyblnet_updated_orig\pyblnet\pyblnet\blnet_conn.py", line 322, in get_latest
    frames.update(self._split_latest(data, frame))
  File "H:\HeimNetzwerk\UVR\pyblnet_updated_orig\pyblnet\pyblnet\blnet_conn.py", line 344, in _split_latest
    frames[frame] = BLNETParser(data[1:LATEST_SIZE + 1])
  File "H:\HeimNetzwerk\UVR\pyblnet_updated_orig\pyblnet\pyblnet\blnet_parser.py", line 76, in __init__
    self._convert_speed(speed[channel]), 3)
TypeError: type NoneType doesn't define __round__ method

Process finished with exit code 1

With the previous version, I did not get this error. I am not sure, what the reason could be...
Could it be related to https://github.com/nielstron/pyblnet/issues/6 ? 

Regards,
Hendrik

**Comment by nielstron** [comment]
The BLNET component seems to use the "direct_ta" protocol. This protocol is not at all supported as of now, so the error is to be expected. Using the protocol has been disabled by default in current versions.

**Comment by nielstron** [comment]
#33 seems to be related

**Comment by zwotzie** [comment]
should be fixed with merged: https://github.com/nielstron/pyblnet/pull/43
